version: '3'
services:
    db:
        image: mongo:latest
        container_name: db
        restart: unless-stopped
        networks:
            - app-network
    express-boilerplate:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: 'no'
        environment:
            - PORT=3030
            - DB_URL=mongodb://db:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false
        ports:
            - '3030:3030'
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
